### ISSUE TITLE
Navbar formatting issue

### ISSUE THREAD

**Issue by jmcduffie32** [LeahW/NewDevATL#16]
It looks like the most recent update broke the Navbar on mobile if you look at the top left corner you'll  see what I mean. 
![screenshot_2015-08-04-15-43-27](https://cloud.githubusercontent.com/assets/6320818/9070930/4ae4aa6c-3ac0-11e5-924a-b0515c037dc7.png)

**Comment by LeahW** [comment]
Hi Jon, I think the last commit fixed this issue. Can you take a look when you get the chance and let me know if anything else is needed?   http://leahw.github.io/NewDevATL/

**Comment by jmcduffie32** [comment]
looks like it fixed the issue. May want to see if you can get the navbar to span the whole width of the page though. It's a bit odd to have margins on the side of it (this part's just my opinion though so if you like it the way it is there's no reason to change it)

**Comment by LeahW** [comment]
Navbar now spans full width of page with no margins. Good catch!

**Comment by GitsAndGlamour** [comment]
I meant to comment on what happened here. My first commit didn't go as smooth as planned and the style sheet failed to update. :( 

I actually just created a php version of the website to make it cleaner and make it easier to create events and future page add-ons. i'll try out formulas tomorrow, but it's working out beautifully so far! 

http://omiewalls.com is the link so you can see it (so you KNOW it won't fail, I tried it on my blogging page first lol). I will create a pull req. ('Slim Framework/Twig-Viewer') in a few.

I still have blocks to make on the main.twig page as well as a footer to make. I should take some time to clean up the code as well.

**Comment by GitsAndGlamour** [comment]
By the way, Jon, if you know a better way to get the search bar back in the corner like you had it, I'd love some help on that. I couldn't figure it out and was 'forced' to throw it at the end of the nav's list items.

**Comment by jmcduffie32** [comment]
I'll see what I can do about the search bar. Also just a heads up, php
won't work on git hub pages so if you merge that with leah's page you'll
break it.

**Comment by GitsAndGlamour** [comment]
noo! so much progress.. :(

**Comment by GitsAndGlamour** [comment]
I guess it's no reason I can't still practice php on my end and toy around with it though.

**Comment by jmcduffie32** [comment]
If you're still wanting to do some kind of templating you could check out
ember or angularjs both are client side javascript so they'll work on
github pages.
